name: image classify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 1"

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: write
  pages: write
  id-token: write

env:
  GIT_USER: Chiichen # change to yourself
  GIT_EMAIL: chiichen@qq.com # change to yourself
  THEME_REPO: lfkdsk/hexo-theme-type
  THEME_BRANCH: main
  TEMPLATE_REPO: lfkdsk/album_template
  TEMPLATE_BRANCE: main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - name: Checkout template repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.TEMPLATE_REPO }}
        ref: ${{ env.TEMPLATE_BRANCE }}
    - name: Checkout public repo
      uses: actions/checkout@v2
      continue-on-error: true # allow error.
      with:
        ref: gh-pages
        path: public
    - name: Checkout gallery repo
      uses: actions/checkout@v2
      continue-on-error: true # allow error.
      with:
        path: gallery
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requires_tf.txt
      continue-on-error: true
    - run: python analysis.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./public
        github_token: ${{ secrets.GITHUB_TOKEN }}
